sudo: false
language: java
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
deploy:
  - provider: releases
    api_key:
      secure: 867be1c23c0b7684e85e9bfe602bee0135c6fb84
    file: build/libs/*
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      repo: Andrew2070/Empires-Mod
      all_branches: true
  - provider: script
    script: gradle curse
    on:
      tags: true
      repo: Andrew2070/Empires-Mod
      all_branches: true
jdk:
 - oraclejdk8
before_install:
  - git submodule update --init --recursive
  - pip install --user codecov
after_success:
  - codecov 
